[project]
name = "secret-santa-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "psycopg[binary]>=3.2.12",
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.5",
]
